### ISSUE TITLE
running NA_pairwise_interactions.py can not load structure

### ISSUE THREAD

**Issue by vreinharz** [BGSU-RNA/fr3d-python#18]
I am trying to run the NA_pairwise_interactions.py directly on ubuntu. 
I just cloned / installed with python install in a `pipenv` environment (btw the file `localpath.py` is in the github and shouldn't :) ). When I try to run the command on two different PDB IDs I get the same error:

`python NA_pairwise_interactions.py -i /srv/rna/PDB/Data/CIF/ 1S72 -o \`pwd\``
> Reading file /srv/rna/PDB/Data/CIF/1S72.cif, which is number 1 out of 1
>   Not able to read /srv/rna/PDB/Data/CIF/1S72.cif
>   Could not load structure 1S72
> Summary of time taken:
> start                          :      0.000 seconds      0.000 minutes      6.951% of total
> Reading CIF files              :      0.000 seconds      0.000 minutes     93.049% of total
> Total                          :      0.000 seconds      0.000 minutes    100.000% of total
> Not able to read these files: [('1S72', '', '')]
> Basepair annotations are not yet finalized

`python NA_pairwise_interactions.py -i /srv/rna/PDB/Data/CIF/ 3E5C -o \`pwd\``

> Reading file /srv/rna/PDB/Data/CIF/3E5C.cif, which is number 1 out of 1
>   Not able to read /srv/rna/PDB/Data/CIF/3E5C.cif
>   Could not load structure 3E5C
> Summary of time taken:
> start                          :      0.000 seconds      0.000 minutes      6.369% of total
> Reading CIF files              :      0.000 seconds      0.000 minutes     93.631% of total
> Total                          :      0.000 seconds      0.000 minutes    100.000% of total
> Not able to read these files: [('3E5C', '', '')]
> Basepair annotations are not yet finalized

**Comment by clzirbel** [comment]
I pushed a commit that will give more information about the cause of file reading errors.  The only way I was able to reproduce the error was with a slow internet connection and a partially-downloaded .cif file.  Hopefully that won't be a common error that people have.

**Comment by vreinharz** [comment]
So that was not the problem but I get more info! I have already all CIF in my computer. 

> 3E5C Could not load structure /srv/rna/PDB/Data/CIF/3E5C.cif due to exception TypeError: startswith first arg must be bytes or a tuple of bytes, not str

**Comment by vreinharz** [comment]
Ok I found the problem.  In `NA_pairwise_interactions.py` on line `175` the file is opened in binary mode only, but I have text files (I look at them by hand). I'll

**Comment by clzirbel** [comment]
Not sure about the history of this, but using Python 3.8 on Windows needs 'rb' because 'r' does not work.  Awkward, but let's get it to work for everyone.

**Comment by clzirbel** [comment]
Looks good, thanks for the new case.
