### ISSUE TITLE
Undefined variable in function `write_unit_data_file` in file `NA_pairwise_interactions`

### ISSUE THREAD

**Issue by vreinharz** [BGSU-RNA/fr3d-python#20]
In the function `write_unit_data_file` there is a loop through all `nucleotides`, but that variable is never initialized. Maybe it should be `structure.nucleotides`?

**Comment by clzirbel** [comment]
That was a work in progress.  That function should work now.  It produces data for the FR3D search tool, which is not yet in this repository.  When that is incorporated, this function will be ready to go.
