### ISSUE TITLE
Use mmcif-pdbx

### ISSUE THREAD

**Issue by tzok** [BGSU-RNA/fr3d-python#5]
The documentation describes a manual approach for installing `pdbx` for Python 3. However, there is a ready-to-use package [`mmcif-pdbx`](https://pypi.org/project/mmcif-pdbx/), which you could list in `setup.py` under `install_requires`.

You would have to adapt `fr3d-python`, because currently there are some API mismatches:
```python
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/fr3d/classifiers/NA-pairwise-interactions.py", line 20, in <module>
    from fr3d.cif.reader import Cif
  File "/usr/local/lib/python3.10/site-packages/fr3d/cif/reader.py", line 18, in <module>
    from pdbx.reader.PdbxReader import PdbxReader as Reader
ModuleNotFoundError: No module named 'pdbx.reader.PdbxReader'; 'pdbx.reader' is not a package
```

Nevertheless, in the long term, it would be much more user-friendly to just install a dependency from PyPI.

**Comment by AntonPetrov** [comment]
Please also see my pull request that build on Tomasz' work to add missing dependencies and pins all versions:
https://github.com/tzok/fr3d-python/pull/2

**Comment by irvingjacob** [comment]
This should be updated and functioning with its original functionality for 2.7 and usable with mmcif-pdbx for python 3.x. Thanks!
