### ISSUE TITLE
Output annotations as text files

### ISSUE THREAD

**Issue by AntonPetrov** [BGSU-RNA/fr3d-python#8]
Currently the annotations are stored as pickle files but it is desirable to be able to generate text files in a tab-separated format.

**Comment by clzirbel** [comment]
NA_pairwise_interactions.py now writes interactions in tab-delimited text format.

________________________________
Craig L. Zirbel
Professor
Department of Mathematics and Statistics
BGSU | Bowling Green State University
Bowling Green, OH 43403
***@***.******@***.***>
www.bgsu.edu/zirbel<http://www.bgsu.edu/zirbel>
________________________________

From: Anton Petrov ***@***.***>
Sent: Monday, April 4, 2022 12:11 PM
To: BGSU-RNA/fr3d-python ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [EXTERNAL] [BGSU-RNA/fr3d-python] Output annotations as text files (Issue #8)


Currently the annotations are stored as pickle files but it is desirable to be able to generate text files in a tab-separated format.

-

**Comment by AntonPetrov** [comment]
I tried running `python fr3d/classifiers/NA_pairwise_interactions.py -i files/1AQ3.cif -o files` but I only get a pickle file. Am I missing something?

**Comment by irvingjacob** [comment]
Sorry, I thought an update got pushed, but it hadn't yet. Should be resolved with last push.

**Comment by AntonPetrov** [comment]
Thanks, it's working now! ✅
